weights:
  kill: 0.5
  money: 0.01
  member_count: 0.1
  events_won: 0.1

events:
  interval: 25 # minutes
  custom-events:
    diamond-mining-competition:
      name: "Diamond Rush"
      description: "Mine 50 diamonds before other factions to claim victory!"
      objectives:
        diamond_mine: 50
      rewards:
        commands:
          - "give {player} diamond_block 1"
        deposit: 5
    faction-warfare:
      name: "Faction Warfare"
      description: "Eliminate 25 enemy faction members to dominate the battlefield!"
      objectives:
        faction_kill: 25
      rewards:
        commands:
          - "give {player} golden_apple 1"
        deposit: 5
    ore-extraction-challenge:
      name: "Ore Extraction Race"
      description: "Extract 500 blocks of ore faster than any other faction!"
      objectives:
        block_mine: 500
      rewards:
        commands:
          - "give {player} emerald 1"
        deposit: 5
    monster-slaying-competition:
      name: "Monster Hunt"
      description: "Slay 250 mobs to prove your faction's combat prowess!"
      objectives:
        mob_kill: 250
      rewards:
        commands:
          - "give {player} enchanted_golden_apple 1"
        deposit: 5
    bountiful-harvest-challenge:
      name: "Bountiful Harvest"
      description: "Harvest 1000 crops before other factions to reap the rewards!"
      objectives:
        crop_harvest: 1000
      rewards:
        commands:
          - "give {player} pumpkin_pie 1"
        deposit: 5
    timber-felling-competition:
      name: "Timber Felling Challenge"
      description: "Gather 2000 logs faster than any other faction!"
      objectives:
        wood_mine: 2000
      rewards:
        commands:
          - "give {player} dark_oak_log 1"
        deposit: 5
    anglers-tournament:
      name: "Angler's Tournament"
      description: "Catch 400 fish before your rivals to claim the title of master angler!"
      objectives:
        fishing: 400
      rewards:
        commands:
          - "give {player} cooked_salmon 1"
        deposit: 5

mysql:
  enabled: true
  url: jdbc:mysql://localhost:3306/database
  username: root
  password: password
