name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
api-version: 1.13
api: 1.13
softdepend: [ PlaceholderAPI, Vault, Dynmap, WorldGuard ]
commands:
  factions:
    description: Faction commands
    usage: /<command> [args]
    aliases: [f, clans, clan, guilds, guild]
